config/routes.rb
Srq::Application.routes.draw do

  # User related routes
  get "sign_up" => "users#new", :as => "sign_up"
  get "user_home" => "users#home", :as => "user_home"
  resources :users

  # Non model Pages
  match 'pages/authenticate' => 'pages#authenticate'
  get "log_in" => "pages#login", :as => "log_in"
  get "log_out" => "pages#logout", :as => "log_out"
  get "contacts" => "pages#contacts", :as => "contacts"


  # Application Root
  root :to => "pages#root"

  # Asin related routes
  get "asins/index"
  match 'asins/index' => 'asins#index'
  get "asins/show"
  match 'asins/show/:id' => 'asins#show'

  get "asin_status" => "asins#status", :as => "asin_status"
  get "research_asin" => "asins#research", :as => "research_asin"
  match 'purchaseorders/purchaseorder_asins' => 'purchaseorders#purchaseorder_asins'

  # Purchaseorder related routes
  get "purchaseorders/index"
  match 'purchaseorders/index' => 'purchaseorders#index'
  get "purchaseorder_home" => "purchaseorders#show", :as => "purchaseorder_home"
  match 'vendors/vendors_purchaseorders' => 'vendors#vendors_purchaseorders'
  get "research_purchaseorder" => "purchaseorders#research", :as => "research_purchaseorder"
  match 'purchaseorders/search' => 'purchaseorders#search'


  # Vendor related routes
  get "vendor_registration" => "vendors#new", :as => "vendor_registration"
  get "vendors_list" => "vendors#index", :as => "vendors_list"
  get "vendor_home" => "vendors#show", :as => "vendor_home"
  get "research_vendor" => "vendors#research", :as => "research_vendor"
  resources :vendors

  # Auto Complete route
  get 'compliances/autocomplete_battery_size_size'

  # Compliance Related routes
  get 'vendor_asin_compliance_home' => "compliances#vendor_asin_compliance_home", :as => 'vendor_asin_compliance_home'
  match 'compliances/copy/:id', :to => 'compliances#copy', :as => "copy_compliance"
  match 'compliances/associate_purchase_orders' => 'compliances#associate_purchase_orders'
  resources :compliances

  # Procurement related routes
  get "procurement_bulk_upload" => "procurements#bulk_upload", :as => "procurement_bulk_upload"
  match "procurements/bulk_process" => "procurements#bulk_process"

  # Bulk Vendor upload related routes
  get "vendor_bulk_upload" => "vendors#bulk_upload", :as => "vendor_bulk_upload"
  match "vendors/bulk_process" => "vendors#bulk_process"

end

app/models/asin.rb
class Asin < ActiveRecord::Base

  # Status - pending_vendor_input, vendor_input_complete, compliance_approved
  belongs_to :purchaseorder
  belongs_to :compliance

  scope :by_sku, lambda { |sku|
    {
      :conditions => { :sku => sku}
    }
  }

  scope :by_vendor, lambda { |vendor|
        joins(:purchaseorder).where("purchaseorders.vendor_id = ?", vendor.id)
  }

  scope :by_compliance, lambda { |compliance|
    {
     :conditions => { :compliance_id => compliance.id }
    }
  }

  scope :unapproved, lambda {
    where("asins.status != 'compliance_approved'")
  }

  def self.search(sku, purchaseorder_id)
    if sku and purchaseorder_id
      find(:first, :conditions => ['sku LIKE ? AND purchaseorder_id LIKE ?', sku, purchaseorder_id])
    else
      find(:all)
    end
  end

  # If a Compliance Set is associated, then the vendor's 'activity for this asin is complete
  # Status is now 'vendor_input_complete' and same might apply to rolled up purchase order's status
  def compliance_associated
    self.status = "vendor_input_complete"
    self.save
    self.purchaseorder.compliance_associated
  end

  # If an associated Compliance Set is approved, then the activity for this asin is complete
  # Status is now 'compliance_approved' and same might apply to rolled up purchase order's status
  def compliance_approved
    self.status = "compliance_approved"
    self.save
    self.purchaseorder.compliance_approved
  end

  # If an associated Compliance Set is rejected, then a new Compliance set with be needed
  # Status is now back to 'pending_vendor_input' and same applies to the rolled up purchase order's status
  def compliance_rejected
    self.compliance_id = nil
    self.status = "pending_vendor_input"
    self.purchaseorder.status = "pending_vendor_input"
    self.save
  end

  def approved?
    self.status.eql?("compliance_approved")
  end

end

app/controllers/asins_controller.rb
class AsinsController < ApplicationController

  before_filter :validated_all

  # TODO See who needs access to this function
  def index
    @asins = Asin.all
  end

  def show
    @asin = Asin.find(params[:id])
  end

  def research
  end

  def status
    if session[:type] == "vendor"
      #  Purchase Orders for the Vendor which contain the ASIN
      @purchaseorders = Vendor.find(session[:id]).sku_purchaseorders(params[:sku])

      # Compliance Sets submitted by the Vendor for the ASIN
      @compliances = Compliance.by_sku(params[:sku]).by_vendor(Vendor.find(session[:id]))
    end

    if session[:type] == "user"
      # All Purchase Orders containing the sku
      @purchaseorders = Purchaseorder.contains_sku(params[:sku])


      # All Compliance Sets for the ASIN submitted by any Vendor
      @compliances = Compliance.by_sku(params[:sku])
    end

    if @purchaseorders.blank? and @compliances.blank?
      flash.now[:alert] = "No Matching Purchase Orders or Compliance Sets  found in the system for the ASIN."
      render "research"
    end
  end

end

app/helpers/asins_helper.rb
module AsinsHelper
end

app/views/asins/_asin.html.haml
- counter = defined?(asin_counter) ? asin_counter : 0
%tr{ :class => css(counter)}
    %td
        = asin.sku
        %table
            %tbody
                %tr
                    %th Title
                    %td
                        = asin.title
                    %tr
                    %th Status
                    %td
                        %strong{ :class =>  asin.status }
                            = asin.status
                    %tr
                    - if pending_vendor_input(asin) and session[:type] == "vendor"
                        %th Create / Associate
                        %td
                            = link_to 'Manage Compliance Set', vendor_asin_compliance_home_path(:sku => asin.sku, :vendor_id => asin.purchaseorder.vendor.id)

                    - elsif pending_vendor_input(asin) and session[:type] == "user"
                        %th Associated Compliance Set
                        %td No Vendor input

                    - else
                        %th Associated Compliance Set
                        %td
                            = link_to 'Compliance Set', asin.compliance

app/views/asins/index.html.erb
<table class="asin_list">
  <tbody>
    <%= render @asins %>
  </tbody>
</table>

app/views/asins/research.html.erb
<div id='container' >

    <%= form_tag(asin_status_path,:method => 'get' ) do %>
        <div class="box">
            <label>
                <span><%= label_tag :sku %></span>
                <%= text_field_tag :sku, params[:sku], :class => "box_textfield" %>
            </label>
        </div>
        <div class="box">
            <label>
            <%= submit_tag 'Research', :class => 'box_button ui-button ui-widget ui-state-default ui-corner-all' %>
            </label>
        </div>

    <% end %>

</div>

app/views/asins/show.html.erb
<%= render @asin %>

app/views/asins/status.html.erb
<h2>Purchase Orders</h2>

<table class="purchaseorder_list">
  <tbody>
    <%= render @purchaseorders %>
  </tbody>
</table>

<h2>Compliance Sets submitted by Vendor for ASIN</h2>

<div class="compliance">
  <table class="compliance_sets">
    <%= render :partial => 'compliances/compliance_summary', :collection => @compliances, :as => :compliance   unless @compliances.empty? %>
  </table>
</div>