config/routes.rb
Srq::Application.routes.draw do

  # User related routes
  get "sign_up" => "users#new", :as => "sign_up"
  get "user_home" => "users#home", :as => "user_home"
  resources :users

  # Non model Pages
  match 'pages/authenticate' => 'pages#authenticate'
  get "log_in" => "pages#login", :as => "log_in"
  get "log_out" => "pages#logout", :as => "log_out"
  get "contacts" => "pages#contacts", :as => "contacts"


  # Application Root
  root :to => "pages#root"

  # Asin related routes
  get "asins/index"
  match 'asins/index' => 'asins#index'
  get "asins/show"
  match 'asins/show/:id' => 'asins#show'

  get "asin_status" => "asins#status", :as => "asin_status"
  get "research_asin" => "asins#research", :as => "research_asin"
  match 'purchaseorders/purchaseorder_asins' => 'purchaseorders#purchaseorder_asins'

  # Purchaseorder related routes
  get "purchaseorders/index"
  match 'purchaseorders/index' => 'purchaseorders#index'
  get "purchaseorder_home" => "purchaseorders#show", :as => "purchaseorder_home"
  match 'vendors/vendors_purchaseorders' => 'vendors#vendors_purchaseorders'
  get "research_purchaseorder" => "purchaseorders#research", :as => "research_purchaseorder"
  match 'purchaseorders/search' => 'purchaseorders#search'


  # Vendor related routes
  get "vendor_registration" => "vendors#new", :as => "vendor_registration"
  get "vendors_list" => "vendors#index", :as => "vendors_list"
  get "vendor_home" => "vendors#show", :as => "vendor_home"
  get "research_vendor" => "vendors#research", :as => "research_vendor"
  resources :vendors

  # Auto Complete route
  get 'compliances/autocomplete_battery_size_size'

  # Compliance Related routes
  get 'vendor_asin_compliance_home' => "compliances#vendor_asin_compliance_home", :as => 'vendor_asin_compliance_home'
  match 'compliances/copy/:id', :to => 'compliances#copy', :as => "copy_compliance"
  match 'compliances/associate_purchase_orders' => 'compliances#associate_purchase_orders'
  resources :compliances

  # Procurement related routes
  get "procurement_bulk_upload" => "procurements#bulk_upload", :as => "procurement_bulk_upload"
  match "procurements/bulk_process" => "procurements#bulk_process"

  # Bulk Vendor upload related routes
  get "vendor_bulk_upload" => "vendors#bulk_upload", :as => "vendor_bulk_upload"
  match "vendors/bulk_process" => "vendors#bulk_process"

end

app/models/compliance.rb
class Compliance < ActiveRecord::Base

  # To prevent creation of a Compliance Set without sku and vendor
  validates :vendor_id, :presence => true
  validates :sku, :presence => true

  has_many :documents, :dependent => :delete_all
  accepts_nested_attributes_for :documents, :allow_destroy => true


  has_many :labs, :dependent => :delete_all
  accepts_nested_attributes_for :labs, :allow_destroy => true

  has_many :packaging_details, :dependent => :delete_all
  accepts_nested_attributes_for :packaging_details, :allow_destroy => true

  has_many :product_details, :dependent => :delete_all
  accepts_nested_attributes_for :product_details, :allow_destroy => true

  has_many :battery_details, :dependent => :delete_all
  accepts_nested_attributes_for :battery_details, :allow_destroy => true

  belongs_to :vendor

  scope :by_vendor, lambda { |vendor|
    {
      :conditions => { :vendor_id => vendor.id }
    }
  }

  scope :by_sku, lambda { |sku|
    {
      :conditions => { :sku => sku}
    }
  }

  scope :by_status, lambda { |status|
    {
      :conditions => { :status => status}
    }
  }

  before_update :send_update_notification


  def is_vendor_editable
    status.eql?("vendor_input")
  end

  def is_user_editable
    status.eql?("user_review")
  end

  def approve
    status = "approved"
    self.save
  end

  def approved?
    status.eql?("approved")
  end

  def rejected
    status = "rejected"
    self.save
  end

  # TODO : Define the method to decide when the compliance set is expired, maybe add a expiry date on the compliance table
  def expired
  end

  def is_vendor_deletable
    is_vendor_editable
  end

  def is_user_deletable
    is_user_editable || Asin.by_compliance(self).empty?
  end



  private
  # Method to generate a notification only when the status of a Compliance Set changes
  def send_update_notification
    puts "Self Status " + self.status + " Currently persisted Status from DB " + Compliance.find(self.id).status + " => Changed " + (self.status_changed?).to_s
    SrqMailer.compliance_update_notification(self.vendor, self.sku, self.status_was, self.status).deliver unless !self.status_changed?
  end

#  TODO: Figure out how to define association to pull up all PO ASINs linked to Compliance Set
# %w[vendor_input user_review approved rejected]

end

app/controllers/compliances_controller.rb
require 'aws/s3'

class CompliancesController < ApplicationController

  autocomplete :battery_size, :size

  before_filter :set_compliance_set_status

  # GET /compliances
  # GET /compliances.xml
  def index
    @compliances = Compliance.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @compliances }
    end
  end

  # GET /compliances/1
  # GET /compliances/1.xml
  def show
    @compliance = Compliance.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @compliance }
    end
  end

  # GET /compliances/new
  # GET /compliances/new.xml
  def new

    @compliance = Compliance.new
    @compliance.status = "vendor_input"
    if params[:sku]
      @compliance.sku = params[:sku]
    end
    if params[:vendor_id]
      @compliance.vendor_id = params[:vendor_id]
    elsif session[:type] == "vendor"
      @compliance.vendor_id = session[:id]
    else
      redirect_to sign_up_path
    end
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @compliance }
    end
  end

  # GET /compliances/1/edit
  def edit
    @compliance = Compliance.find(params[:id])
  end

  # POST /compliances
  # POST /compliances.xml
  def create
    begin
      if !params[:compliance][:documents_attributes].nil? then
        bucket_name = "Vendors/" + Vendor.find(session[:id]).code + "/" + params[:compliance][:sku] + "/" + (Time.now.to_i).to_s

        params[:compliance][:documents_attributes].each { |key, value|
          # key, binary_object, bucket_name --> can be replaced by store_object(bucket, key, object)
          aws_connection_instance = AmazonS3Asset.new
          aws_connection_instance.store_object(bucket_name, value["file"].original_filename, value["file"])

          value["url"] = "http://s3.amazonaws.com/" + bucket_name + "/" + value["file"].original_filename
          value.delete("file")
        }
      end
      @compliance = Compliance.new(params[:compliance])
      @compliance.last_activity_at = Time.now

      respond_to do |format|
        if @compliance.save
          format.html { redirect_to vendor_asin_compliance_home_path(:sku => @compliance.sku, :vendor_id => @compliance.vendor_id) }
        else
          format.html { render :action => "new" }
        end
      end
    rescue AWS::S3::ResponseError => error
      puts "AWS S3 Response Error Occured"
      raise
    rescue
      if !params[:compliance][:documents_attributes].nil? then
        params[:compliance][:documents_attributes] = {}
      end
      @compliance = Compliance.new(params[:compliance])
      flash.now[:alert] = "An Error occurred during the creation of Compliance Set, Please resubmit with lesser upload files."
      render "new"
    end
  end

  # PUT /compliances/1
  # PUT /compliances/1.xml
  def update

    @compliance = Compliance.find(params[:id])

    # Vendor Session
    if vendor_session?
      if !params[:compliance][:documents_attributes].nil? then
        if @compliance.documents.nil? || @compliance.documents.empty?
          bucket_name = "Vendors/" + Vendor.find(session[:id]).code + "/" + params[:compliance][:sku] + "/" + (Time.now.to_i).to_s
        else
          bucket_name = "Vendors/" + Vendor.find(session[:id]).code + "/" + params[:compliance][:sku] + "/" + @compliance.documents.first.url.rpartition("/")[0].rpartition("/")[2]
        end

        params[:compliance][:documents_attributes].each { |key, value|
          if value.has_key?("file") then
            begin

              # key, binary_object, bucket_name --> can be replaced by store_object(bucket, key, object)
              aws_connection_instance = AmazonS3Asset.new
              aws_connection_instance.store_object(bucket_name, value["file"].original_filename, value["file"])

              value["url"] = "http://s3.amazonaws.com/" + bucket_name + "/" + value["file"].original_filename
              value.delete("file")
            rescue
              params[:compliance][:documents_attributes] = {} unless params[:compliance][:documents_attributes].nil?
              @compliance = Compliance.find(params[:id])
              flash.now[:alert] = "An Error occurred during the update of Compliance Set, Please resubmit with lesser upload files."
              render "edit"
              return
            end
          end
        }
      end

      @compliance.last_activity_at = Time.now

      respond_to do |format|
        if @compliance.update_attributes(params[:compliance])
          format.html {
            redirect_to vendor_asin_compliance_home_path(:sku => @compliance.sku, :vendor_id => @compliance.vendor_id)
          }

          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @compliance.errors, :status => :unprocessable_entity }
        end
      end
    else
      # User Session

      if !params[:compliance][:comments_internal].nil? and !@compliance.comments_internal.eql?(params[:compliance][:comments_internal]) then
        @compliance.comments_internal = params[:compliance][:comments_internal]
      end

      if !params[:compliance][:comments_external].nil? and !@compliance.comments_external.eql?(params[:compliance][:comments_external]) then
        @compliance.comments_external = params[:compliance][:comments_external]
      end

      # User approves Compliance Set
      if !params[:compliance][:status].nil? and params[:compliance][:status].eql?("approved") and !"approved".eql?(@compliance.status)
        @compliance.status = "approved"
        # Approve all Purchase Order Asins associated with the Compliance Set
        Asin.by_compliance(@compliance).each do |asin|
          asin.compliance_approved
        end
      end

      # User Rejects Compliance Set
      if !params[:compliance][:status].nil? and params[:compliance][:status].eql?("rejected") and !"rejected".eql?(@compliance.status)
        @compliance.status = "rejected"
        # Clear any associations that Purchase Order Asins have with this Compliance Set
        Asin.by_compliance(@compliance).each do |asin|
          asin.compliance_rejected
        end
      end

      # User Moves Compliance Set back to Vendor
      if !params[:compliance][:status].nil? and params[:compliance][:status].eql?("vendor_input") and !"vendor_input".eql?(@compliance.status)
        @compliance.status = "vendor_input"
        # Passing the Compliance Set back to the Vendor should not have any impact
      end

      @compliance.last_activity_at = Time.now

      respond_to do |format|
        if @compliance.save
          format.html {
            redirect_to user_home_path
          }
          format.xml  { head :ok }
        else
          # TODO Fix this
          format.html { render :action => "edit" }
          format.xml  { render :xml => @compliance.errors, :status => :unprocessable_entity }
        end
      end

    end

  end

  # DELETE /compliances/1
  # DELETE /compliances/1.xml
  def destroy
    @compliance = Compliance.find(params[:id])

    # Any asins that are linked with the compliance set being deleted need to be freed
    Asin.by_compliance(@compliance).each do |asin|
      asin.compliance_rejected
    end
    vendor_id = @compliance.vendor_id
    sku = @compliance.sku
    @compliance.destroy

    respond_to do |format|
      format.html {
        redirect_to vendor_asin_compliance_home_path(:vendor_id => vendor_id, :sku => sku) if vendor_session?
        redirect_to user_home_path if !vendor_session?
      }
      format.xml  { head :ok }
    end
  end

  def vendor_asin_compliance_home


    @compliances_user = Compliance.by_status("user_review")
    @compliances_user = @compliances_user.by_vendor(Vendor.find(params[:vendor_id])) if params[:vendor_id]
    @compliances_user = @compliances_user.by_sku(params[:sku]) if params[:sku]

    @compliances_approved = Compliance.by_status("approved")
    @compliances_approved = @compliances_approved.by_vendor(Vendor.find(params[:vendor_id])) if params[:vendor_id]
    @compliances_approved = @compliances_approved.by_sku(params[:sku]) if params[:sku]

    @compliances_vendor = Compliance.by_status("vendor_input")
    @compliances_vendor = @compliances_vendor.by_vendor(Vendor.find(params[:vendor_id])) if params[:vendor_id]
    @compliances_vendor = @compliances_vendor.by_sku(params[:sku]) if params[:sku]


    @compliances = @compliances_vendor | @compliances_user | @compliances_approved

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @compliances }
    end

  end

  def associate_purchase_orders
    compliance = Compliance.find(params[:compliance_id])
    @vendor = compliance.vendor
    params[:asins].each do |asin|
      asin = Asin.find(asin)
      asin.compliance = compliance
      if compliance.approved?
        asin.compliance_approved
      else
        asin.compliance_associated
      end
    end
    redirect_to vendor_home_path
  end

  def copy
     #Override Clone
    compliance_existing = Compliance.find(params[:id])
    @compliance = compliance_existing.clone
    compliance_existing.labs.each do |existing_lab|
      @compliance.labs << existing_lab.clone
    end
    compliance_existing.documents.each do |existing_document|
      @compliance.documents << existing_document.clone
    end
    @compliance.status = "vendor_input"
    @compliance.save
    flash[:notice] = 'I can haz the Copies and copies ...mmmmm !!!'
    render "edit"
  end


  private
  def set_compliance_set_status

    if "Save Compliance Set details".eql?(params[:commit])
      params[:compliance][:status] = "vendor_input"
    end
    if "Submit for Review".eql?(params[:commit])
      params[:compliance][:status] = "user_review"
    end
        #%w[vendor_input user_review approved rejected]
  end

end

app/helpers/compliances_helper.rb
module CompliancesHelper
end

app/views/compliances/_battery_detail.html.erb
<table>
  <tbody>
  <tr>
    <th colspan="2">
        Battery Type
    </th>
    <td colspan="4">
        <%= battery_detail.battery_type %>
    </td>
  </tr>
  <tr>
    <th>
        Battery Size
    </th>
    <td>
        <%= battery_detail.size %>
    </td>

    <th>
        Battery Units
    </th>
    <td>
        <%= battery_detail.units %>
    </td>

    <th>
        Battery weight (GR)
    </th>
    <td>
        <%= battery_detail.battery_wt %>
    </td>
  </tr>
  <tr>
    <th colspan="2">
        Battery Packaging Type
    </th>
    <td colspan="4">
        <%= battery_detail.packaging %>
    </td>
  </tr>
  <tr>
    <th colspan="2">
        Battery Brand Name
    </th>
    <td colspan="4">
        <%= battery_detail.brand %>
    </td>
  </tr>

 </tbody>
</table>

app/views/compliances/_compliance_summary.html.erb
<tr>
  <td>
    <div class="compliance_set" id="compliance_set_<%= compliance.id %>">
      <table class="csheader">
        <tr>
          <th><h3>Compliance Set</h3></th>
          <% if session[:type] == "vendor" then %>
              <td align="right">
                Use this Compliance Set <%= radio_button_tag 'compliance_set_selector', compliance.id, false, :class => "compliance_set_selector_radio" %>
              </td>
          <% end %>

        </tr>
      </table>
      <table class="csdata">
        <tr>
          <th>Last Activity:</th>
          <td><%= compliance.last_activity_at %></td>
        </tr>
        <tr>
          <th>Notes:</th>
          <td><form><textarea cols="50" rows="3" readonly="true"><%= compliance.vendor_notes %></textarea></form></td>
        </tr>
        <tr>
          <th>Status:</th>
          <td><%= compliance.status %></td>
        </tr>
        <tr>
          <th>Submitter:</th>
          <td><%= compliance.esignature %></td>
        </tr>



          <% if session[:type] == "vendor" then %>
              <tr id="associate_pos_form_<%= compliance.id %>" class="associate_poid_form">
                <td colspan="2">
                <h3>Associate Purchase Orders:</h3>
                  <table>
                  <%= form_tag( { :controller => "compliances", :action => "associate_purchase_orders" }, :method => :put) do %>
                        <!-- Make sure already approved / associated asins are treated differently -->
                        <!-- remove compliance_approved asins from display  by checking status as they are already associated with a compliance_approved compliance set from the vendor -->
                        <!-- set the checked status if asin is already associated with the current compliance set -->
                      <% Asin.by_vendor(Vendor.find(session[:id])).by_sku(compliance.sku).unapproved.each do |asin|  %>
                        <tr>
                          <th> <%=  asin.purchaseorder.code %></th>
                            <td>
                              <%= check_box_tag( "asins[]", value = asin.id, checked = (asin.compliance == compliance) ) %>
                              <%= hidden_field_tag 'compliance_id', compliance.id %>
                            </td>
                        </tr>
                      <% end %>
                      <tr>
                        <td colspan="2">
                          <%= submit_tag( "Associate", :class => "button") %>
                        </td>
                      </tr>
                  <% end %>
                  </table>
                </td>
              </tr>
          <% end %>




        <tr>
          <th>View Details</th>
          <td><%= link_to 'Show', compliance %></td>
        </tr>

        <% if (session[:type].eql?("vendor") and compliance.is_vendor_editable) or !session[:type].eql?("vendor") then %>
            <tr>
              <th>Edit Details</th>
              <td><%= link_to 'Edit', edit_compliance_path(compliance) %></td>
            </tr>
        <% end %>


        <% if session[:type].eql?("vendor") then %>
            <tr>
              <th>Clone Compliance Set</th>
              <td><%= link_to 'Clone', copy_compliance_path(compliance)  %></td>
            </tr>
        <% end %>

        <% if is_compliance_deletable(compliance) then %>
            <tr>
              <th>Delete Compliance Set</th>
              <td><%= link_to 'Destroy', compliance, :confirm => 'Are you sure?', :method => :delete %></td>
            </tr>
        <% end %>



      </table>
    </div>
  </td>
</tr>

app/views/compliances/_compliances.html.erb
<% if !compliances.blank? then %>
    <h1>Compliance Sets for ASIN <%= compliances.first.sku %> from Vendor <%= compliances.first.vendor.code %></h1>
    <table>
      <tr>
        <th>Select Me</th>
        <th>Sku</th>
        <th>Vendor</th>
        <th>Status</th>
        <th>Last activity at</th>
        <th></th>
        <th></th>
        <th></th>
        <th>DIV</th>
      </tr>
      <% compliances.each do |compliance| %>
          <tr>
            <td>


              <%= radio_button_tag 'compliance_set_selector', compliance.id, true, :class => "compliance_set_selector_radio" %>


            </td>
            <td><%= compliance.sku %></td>
            <td><%= compliance.vendor.code %></td>
            <td><%= compliance.status %></td>
            <td><%= compliance.last_activity_at %></td>
            <td><%= link_to 'Show', compliance %></td>
            <td><%= link_to 'Edit', edit_compliance_path(compliance) %></td>
            <td><%= link_to 'Destroy', compliance, :confirm => 'Are you sure?', :method => :delete %></td>
            <td>
              <div id="compliance_set_div_<%= compliance.id %>">
              </div>

            </td>
          </tr>
      <% end %>
    </table>
<% else %>
    <h1> No Matching Compliance Sets found </h1>
<% end %>

app/views/compliances/_document.html.erb
<table class="compliance_docs">
<tbody>
    <tr>
        <th>
            Document URL
        </th>
        <td>
            <%=  link_to document.url,  document.url, :target => "_blank" %>
        </td>
    </tr>
</tbody>
</table>

app/views/compliances/_lab.html.erb
<table class="compliance_tests">
<tbody>
    <tr>
        <th>
            Lab Information
        </th>
        <td>
            <%= lab.info %>
        </td>
    </tr>

    <tr>
        <th>
            Testing Date
        </th>
        <td>
            <%= lab.testing_date %>
        </td>
    </tr>

    <tr>
        <th>
            Report Number
        </th>
        <td>
            <%= lab.report_number %>
        </td>
    </tr>

    <tr>
        <th>
            Standards
        </th>
        <td>
            <%= lab.standards %>
        </td>
    </tr>
</tbody>
</table>

app/views/compliances/_packaging_data.html.erb
<table>
  <tbody>

  <tr>
    <th>
      Paper Cardboard Weight
    </th>
    <td>
      <%= packaging_data.paper_cardboard_wt %>
    </td>
    <th>
      Plastic Weight
    </th>
    <td>
      <%= packaging_data.plastic_wt %>
    </td>
    <th>
      Other Weight
    </th>
    <td>
      <%= packaging_data.other_wt %>
    </td>
  </tr>

  </tbody>
</table>

app/views/compliances/_packaging_detail.html.erb
<table>
  <tbody>

  <tr>
    <th>
      Paper Cardboard Weight
    </th>
    <td>
      <%= packaging_detail.paper_cardboard_wt %>
    </td>
    <th>
      Plastic Weight
    </th>
    <td>
      <%= packaging_detail.plastic_wt %>
    </td>
    <th>
      Other Weight
    </th>
    <td>
      <%= packaging_detail.other_wt %>
    </td>
  </tr>

  </tbody>
</table>

app/views/compliances/_product_detail.html.erb
<table>
  <tbody>

  <tr>
    <th>
      WEEE Category
    </th>
    <td>
      <%= product_detail.weee_category %>
    </td>
    <th>
      Net Product Weight (GR)
    </th>
    <td>
      <%= product_detail.net_product_wt %>
    </td>
  </tr>

  </tbody>
</table>

app/views/compliances/edit.html.erb
<%= render 'form' %>

app/views/compliances/index.html.erb
<div class="compliance">
  <table class="compliance_sets">
    <%= render :partial => 'compliance_summary', :collection => @compliances, :as => :compliance   unless @compliances.empty? %>
  </table>
</div>

<div class="compliance">
  <%= link_to "New Compliance Set", new_compliance_path(:sku => @sku, :vendor_id => @vendor_id) %>
</div>

app/views/compliances/new.html.erb
<%= render 'form' %>

app/views/compliances/show.html.erb
<p id="notice"><%= notice %></p>
<!--TODo : Extract as a header for compliance set pages-->
<div class="compliance">
  <table class="compliance_sets">
    <tr>
      <td>
        Vendor
      </td>
      <td>
        <%= Vendor.find(@compliance.vendor_id).code  %>
      </td>
    </tr>
    <tr>
      <td>
        Sku
      </td>
      <td>
        <%= @compliance.sku %>
      </td>
    </tr>

    <% if (session[:type].eql?("vendor") and @compliance.is_vendor_editable) or !session[:type].eql?("vendor") then %>
        <tr>
          <td>Edit this Compliance Set</td>
          <td><%= link_to 'Edit', edit_compliance_path(@compliance) %></td>
        </tr>
    <% end %>

    <% if is_compliance_deletable(@compliance) then %>
        <tr>
          <td>Delete this Compliance Set</td>
          <td><%= link_to 'Destroy', @compliance, :confirm => 'Are you sure?', :method => :delete %></td>
        </tr>
    <% end %>



  </table>
</div>




<div class="compliance_form">
    <div class="asin_data">
        <table>
        <tbody>
            <tr>
                <th>
                    ASIN
                </th>
                <td>
                    <%= @compliance.sku %>
                </td>
            </tr>

            <tr>
                <th>
                    Vendor Product Number
                </th>
                <td>
                    <%= @compliance.vendor_product_number %>
                </td>
            </tr>

            <tr>
                <th>
                    Brand
                </th>
                <td>
                    <%= @compliance.brand %>
                </td>
            </tr>

            <tr>
                <th>
                    Vendor
                </th>
                <td>
                    <%= Vendor.find(@compliance.vendor_id).code  %>
                </td>
            </tr>

            <tr>
                <th>
                    Status
                </th>
                <td>
                    <%= @compliance.status %>
                </td>
            </tr>

        </tbody>
        </table>
    </div>


    <!-- Associated Packaging Data Details -->
    <div class="wee_data">

    <%= render :partial => 'packaging_detail', :collection => @compliance.packaging_details %>

    </div>

  <!-- Associated WEEEE Product Data Details -->
  <div class="wee_data">

  <%= render :partial => 'product_detail', :collection => @compliance.product_details %>

  </div>


  <!-- Associated Battery Details -->
  <div class="wee_data">

  <%= render :partial => 'battery_detail', :collection => @compliance.battery_details %>

  </div>


    <!-- Associated Lab Details -->
    <div class="compliance_tests">

    <%= render :partial => "lab", :collection => @compliance.labs %>

    </div>

    <!-- Associated Document Details -->
    <div class="compliance_docs">

    <%= render :partial => "document", :collection => @compliance.documents %>

    </div>

    <div class="record_data">
        <table>
        <tbody>
            <tr>
                <th>
                    Availability in European Countries
                </th>
                <td>
                    <%= @compliance.efn_availability %>
                </td>
            </tr>

            <tr>
                <th>
                    Restriction for the following Countries
                </th>
                <td>
                    <%= @compliance.efn_restrictions %>
                </td>
            </tr>

            <tr>
                <th>
                    Reason of Country Restriction
                </th>
                <td>
                    <%= @compliance.efn_restriction_reason %>
                </td>
            </tr>

            <tr>
                <th>
                    Importer of Record
                </th>
                <td>
                    <%= @compliance.importer_of_record %>
                </td>
            </tr>

            <tr>
                <th>
                    Keeper of Record
                </th>
                <td>
                    <%= @compliance.keeper_of_record %>
                </td>
            </tr>

            <tr>
                <th>
                    Manufacture Date
                </th>
                <td>
                    <%= @compliance.manufacture_date %>
                </td>
            </tr>

            <tr>
                <th>
                    Manufacture Place
                </th>
                <td>
                    <%= @compliance.manufacture_place %>
                </td>
            </tr>

            <tr>
                <th>
                    Esignature
                </th>
                <td>
                    <%= @compliance.esignature %>
                </td>
            </tr>

            <tr>
                <th>
                    Position in Company
                </th>
                <td>
                    <%= @compliance.position %>
                </td>
            </tr>

            <% if session[:type] == "user" then %>
                <tr>
                    <th>
                        Comments (Internal)
                    </th>
                    <td>
                        <%= @compliance.comments_internal %>
                    </td>
                </tr>
            <% end %>

            <tr>
                <th>
                    Comments (External)
                </th>
                <td>
                    <%= @compliance.comments_external %>
                </td>
            </tr>

            <tr>
                <th>
                    Vendor Notes
                </th>
                <td>
                    <%= @compliance.vendor_notes %>
                </td>
            </tr>

          </tbody>
        </table>
    </div>


</div>

app/views/compliances/vendor_asin_compliance_home.html.erb
<h2> Management Page for Compliance Set</h2><br/><br/>
<div class="compliance">
  <table class="compliance_sets">
    <tr>
      <td>
        Vendor
      </td>
      <td>
        <%= Vendor.find(params[:vendor_id]).code unless params[:vendor_id].nil? %>
      </td>
    </tr>
    <tr>
      <td>
        Sku
      </td>
      <td>
        <%= params[:sku] unless params[:sku].nil? %>
      </td>
    </tr>
    <% if params[:vendor_id] && params[:sku] then %>
        <tr>
          <td>
            Create a new Compliance Set
          </td>
          <td>
            <%= link_to "New Compliance Set", new_compliance_path(:sku => params[:sku], :vendor_id => params[:vendor_id]) %>
          </td>
        </tr>
    <% end %>
  </table>
</div>

<div class="compliance">
  <h3> <%= "Listing Vendor Owned Compliance Sets" unless @compliances_vendor.empty? %> </h3>
  <table class="compliance_sets">
    <%= render :partial => 'compliance_summary', :collection => @compliances_vendor, :as => :compliance   unless @compliances_vendor.empty? %>
  </table>
</div>

<div class="compliance">
  <h3> <%= "Listing User Owned Compliance Sets" unless @compliances_user.empty? %> </h3>
  <table class="compliance_sets">
    <%= render :partial => 'compliance_summary', :collection => @compliances_user, :as => :compliance   unless @compliances_user.empty? %>
  </table>
</div>

<div class="compliance">
  <h3> <%= "Listing User Approved Compliance Sets" unless @compliances_approved.empty? %> </h3>
  <table class="compliance_sets">
    <%= render :partial => 'compliance_summary', :collection => @compliances_approved, :as => :compliance   unless @compliances_approved.empty? %>
  </table>
</div>