config/routes.rb
Srq::Application.routes.draw do

  # User related routes
  get "sign_up" => "users#new", :as => "sign_up"
  get "user_home" => "users#home", :as => "user_home"
  resources :users

  # Non model Pages
  match 'pages/authenticate' => 'pages#authenticate'
  get "log_in" => "pages#login", :as => "log_in"
  get "log_out" => "pages#logout", :as => "log_out"
  get "contacts" => "pages#contacts", :as => "contacts"


  # Application Root
  root :to => "pages#root"

  # Asin related routes
  get "asins/index"
  match 'asins/index' => 'asins#index'
  get "asins/show"
  match 'asins/show/:id' => 'asins#show'

  get "asin_status" => "asins#status", :as => "asin_status"
  get "research_asin" => "asins#research", :as => "research_asin"
  match 'purchaseorders/purchaseorder_asins' => 'purchaseorders#purchaseorder_asins'

  # Purchaseorder related routes
  get "purchaseorders/index"
  match 'purchaseorders/index' => 'purchaseorders#index'
  get "purchaseorder_home" => "purchaseorders#show", :as => "purchaseorder_home"
  match 'vendors/vendors_purchaseorders' => 'vendors#vendors_purchaseorders'
  get "research_purchaseorder" => "purchaseorders#research", :as => "research_purchaseorder"
  match 'purchaseorders/search' => 'purchaseorders#search'


  # Vendor related routes
  get "vendor_registration" => "vendors#new", :as => "vendor_registration"
  get "vendors_list" => "vendors#index", :as => "vendors_list"
  get "vendor_home" => "vendors#show", :as => "vendor_home"
  get "research_vendor" => "vendors#research", :as => "research_vendor"
  resources :vendors

  # Auto Complete route
  get 'compliances/autocomplete_battery_size_size'

  # Compliance Related routes
  get 'vendor_asin_compliance_home' => "compliances#vendor_asin_compliance_home", :as => 'vendor_asin_compliance_home'
  match 'compliances/copy/:id', :to => 'compliances#copy', :as => "copy_compliance"
  match 'compliances/associate_purchase_orders' => 'compliances#associate_purchase_orders'
  resources :compliances

  # Procurement related routes
  get "procurement_bulk_upload" => "procurements#bulk_upload", :as => "procurement_bulk_upload"
  match "procurements/bulk_process" => "procurements#bulk_process"

  # Bulk Vendor upload related routes
  get "vendor_bulk_upload" => "vendors#bulk_upload", :as => "vendor_bulk_upload"
  match "vendors/bulk_process" => "vendors#bulk_process"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Srq</title>
  <%= stylesheet_link_tag 'css.css', 'jquery.jgrowl', 'jquery-ui-1.8.14.custom' %>
  <%= javascript_include_tag 'jquery.js', 'jquery-ui-1.8.14.custom.min', 'autocomplete-rails', 'rails.js', 'application', 'nested_form', 'jquery.jgrowl', 'jquery.form', 'jquery.remotipart' %>
  <%= csrf_meta_tag %>
</head>
<body>



<div class="title_box">
<h1>SRQ v2.0</h1>
</div>



<div class="actions_bar">

    <ul>
        <% if session[:type] == "vendor" %>
            <li>
                Hi <%= Vendor.find(session[:id]).code %>
            </li>
            <li>
                <%= link_to "Home", vendor_home_path %>
            </li>
            <li>
              <%= link_to "Detail View", vendor_home_path(:detail => true) %>
            </li>
            <li>
                <%= link_to "New Compliance Set", new_compliance_path %>
            </li>

        <% end %>

        <% if session[:type] == "user" %>
            <li>
                Hi <%= User.find(session[:id]).username %>
            </li>
            <li>
                <%= link_to "View All Vendors", vendors_list_path %>
            </li>
            <li>
              <%= link_to "New Vendors", vendor_bulk_upload_path %>
            </li>
            <li>
              <%= link_to "Procurement Data", procurement_bulk_upload_path %>
            </li>
            <li>
              <%= link_to "Research Vendor", research_vendor_path %>
            </li>
        <% end %>

        <li>
          <%= link_to "Research PO", research_purchaseorder_path %>
        </li>
        <li>
            <%= link_to "Research Asin", research_asin_path %>
        </li>

        <li>
            <%= link_to 'Log Out', log_out_path %>
        </li>
    </ul>
</div>

<div class="core">

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>

    <%= yield %>

    <div id='loading'>
        <%= image_tag "spinner.gif" %>
    </div>

</div>




</body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Srq</title>
  <%= stylesheet_link_tag 'css.css', 'jquery.jgrowl', 'jquery-ui-1.8.14.custom' %>
  <%= javascript_include_tag 'jquery.js', 'jquery-ui-1.8.14.custom.min', 'autocomplete-rails', 'rails.js', 'application', 'nested_form', 'jquery.jgrowl', 'jquery.form', 'jquery.remotipart' %>
  <%= csrf_meta_tag %>
</head>
<body>



<div class="title_box">
<h1>SRQ v2.0</h1>
</div>


<div class="actions_bar">

   <ul>
     <li>
       <%= link_to 'Register a new Vendor', vendor_registration_path %>
     </li>
     <li>
       <%= link_to 'Register a new User', sign_up_path %>
     </li>
     <li>
        <%= link_to 'Log In', log_in_path %>
     </li>
     <li>
        <%= link_to 'Contacts', contacts_path %>
     </li>
   </ul>
</div>

<div class="core">

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>

    <%= yield %>
</div>




</body>
</html>